services:
  server:
    build: test-integration/docker/server
    volumes:
      - type: volume
        source: keygen
        target: /keys
    tmpfs:
      - /tmp
    ports:
      - "10022:22"
      - "10080:80"
      - "10443:443"
  client:
    build:
      context: test-integration/docker/client
      args:
        JAVA: 17
        JDKVER: jdk_17.0.14.0.0+7-1
        GRADLE: 8.13
    depends_on:
      server:
        condition: service_started
    volumes:
      - type: bind
        source: .
        target: /code
      - type: volume
        source: keygen
        target: /keys
        read_only: true
      - type: volume
        source: gradle-cache
        target: /gradle-cache
      - /workdir
    tmpfs:
      - /tmp:mode=1777
    environment:
      DURATION: ${DURATION:-2400}
      TYPE: ${TYPE:-GIT}
    user: "${UID:-1000}:${GID:-1000}"
volumes:
  keygen:
  gradle-cache:
