name: Run checkstyle

on: [push, pull_request]

jobs:
  checkstyle:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'
    - name: run spotbugs
      uses: gradle/gradle-build-action@v2
      with:
        arguments: spotbugsMain spotbugsTest
    - uses: jwgmeligmeyling/spotbugs-github-action@master
      name: annotate spotbugs warnings/errors
      if: ${{ failure() || success() }}
      with:
        path: '**/build/spotbugs/*.xml'
